import type { CollectionConfig } from 'payload'

import { isAdmin, isEditor, publishedOrEditor } from '@/access'

export const DevFestEditions: CollectionConfig = {
  slug: 'devfest-editions',
  labels: { singular: 'DevFest page', plural: 'DevFest pages' },
  access: {
    create: isEditor,
    delete: isAdmin,
    read: publishedOrEditor,
    update: isEditor,
  },
  admin: {
    defaultColumns: ['title', 'event', 'year', 'status', '_status', 'updatedAt'],
    description: 'Optional campaign presentation for a canonical event. Dates, venue, sessions and live operations belong to the linked event.',
    useAsTitle: 'title',
  },
  fields: [
    {
      name: 'event',
      type: 'relationship',
      relationTo: 'community-events',
      filterOptions: { eventKind: { equals: 'devfest' } },
      admin: { description: 'The single canonical DevFest event record used across the website.' },
    },
    { name: 'title', type: 'text', required: true },
    { name: 'year', type: 'number', required: true, unique: true },
    { name: 'slug', type: 'text', required: true, unique: true, index: true },
    {
      name: 'status',
      label: 'Event phase',
      type: 'select',
      enumName: 'enum_devfest_editions_event_phase',
      defaultValue: 'announcement',
      required: true,
      options: [
        { label: 'Announcement', value: 'announcement' },
        { label: 'Call for papers open', value: 'cfp-open' },
        { label: 'Registration open', value: 'registration-open' },
        { label: 'Live', value: 'live' },
        { label: 'Ended', value: 'ended' },
      ],
    },
    {
      name: 'hero',
      type: 'group',
      fields: [
        { name: 'eyebrow', type: 'text', defaultValue: 'Karibu Nairobi' },
        { name: 'headline', type: 'text', defaultValue: 'The future', required: true },
        { name: 'accentLine', type: 'text', defaultValue: 'grows here.', required: true },
        { name: 'description', type: 'textarea', required: true },
        { name: 'artwork', type: 'upload', relationTo: 'media' },
        {
          name: 'signals',
          type: 'array',
          maxRows: 3,
          fields: [{ name: 'label', type: 'text', required: true }],
        },
        { name: 'scrollLabel', type: 'text', defaultValue: 'Scroll to grow' },
      ],
    },
    {
      name: 'eventDetails',
      type: 'group',
      fields: [
        { name: 'startsAt', type: 'date' },
        { name: 'endsAt', type: 'date' },
        { name: 'venueName', type: 'text' },
        { name: 'address', type: 'textarea' },
        { name: 'mapURL', type: 'text' },
        { name: 'locationLabel', type: 'text', defaultValue: 'Nairobi, Kenya' },
      ],
    },
    {
      name: 'callsToAction',
      type: 'array',
      maxRows: 3,
      fields: [
        { name: 'label', type: 'text', required: true },
        { name: 'url', type: 'text', required: true },
        {
          name: 'style',
          type: 'select',
          defaultValue: 'primary',
          options: ['primary', 'secondary', 'text'],
        },
      ],
    },
    {
      name: 'ticker',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        {
          name: 'items',
          type: 'array',
          maxRows: 10,
          fields: [{ name: 'label', type: 'text', required: true }],
        },
      ],
    },
    {
      name: 'storySection',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'kicker', type: 'text', defaultValue: 'Community-led, Nairobi-built' },
        { name: 'heading', type: 'text', defaultValue: 'A local home for people who build.' },
        {
          name: 'paragraphs',
          type: 'array',
          dbName: 'story_paragraphs',
          maxRows: 4,
          fields: [{ name: 'text', type: 'textarea', required: true }],
        },
        { name: 'quote', type: 'text', defaultValue: 'There is a seat for you here.' },
      ],
    },
    {
      name: 'tracksSection',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'kicker', type: 'text', defaultValue: 'What grows here' },
        { name: 'heading', type: 'textarea', defaultValue: 'Four paths.\nOne ecosystem.' },
        { name: 'intro', type: 'textarea' },
      ],
    },
    {
      name: 'tracks',
      type: 'array',
      maxRows: 8,
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'description', type: 'textarea', required: true },
        { name: 'accent', type: 'select', options: ['blue', 'red', 'yellow', 'green'], required: true },
        { name: 'topics', type: 'text', hasMany: true },
      ],
    },
    {
      name: 'experienceSection',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'kicker', type: 'text', defaultValue: 'The experience' },
        { name: 'heading', type: 'textarea', defaultValue: 'Make it.\nThen meet around it.' },
        { name: 'marker', type: 'text', defaultValue: '2' },
        { name: 'markerLabel', type: 'textarea', defaultValue: 'Ways to\ngo deep' },
        {
          name: 'items',
          type: 'array',
          dbName: 'experience_items',
          maxRows: 4,
          fields: [
            { name: 'eyebrow', type: 'text', required: true },
            { name: 'title', type: 'text', required: true },
            { name: 'description', type: 'textarea', required: true },
          ],
        },
      ],
    },
    {
      name: 'cfpSection',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'badge', type: 'text', defaultValue: 'CFP / 2026' },
        { name: 'kicker', type: 'text', defaultValue: 'Bring your voice' },
        { name: 'heading', type: 'textarea' },
        { name: 'description', type: 'textarea' },
        { name: 'ctaLabel', type: 'text', defaultValue: 'Register your interest' },
        { name: 'ctaURL', type: 'text' },
        { name: 'artLabelTop', type: 'text', defaultValue: 'Your story' },
        { name: 'artLabelBottom', type: 'text', defaultValue: 'Our stage' },
      ],
    },
    {
      name: 'eventsSection',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'kicker', type: 'text', defaultValue: 'The root system' },
        { name: 'heading', type: 'text', defaultValue: 'The community never stops.' },
        { name: 'allEventsLabel', type: 'text', defaultValue: 'All GDG Nairobi events' },
        { name: 'allEventsURL', type: 'text', defaultValue: 'https://gdg.community.dev/gdg-nairobi/' },
        { name: 'syncNote', type: 'text' },
      ],
    },
    {
      name: 'highlightsSection',
      label: 'Past event gallery & videos',
      type: 'group',
      admin: { description: 'Curate the homepage photo wall and up to three featured videos.' },
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'kicker', type: 'text', defaultValue: 'Previously, in Nairobi' },
        { name: 'heading', type: 'text', defaultValue: 'Made by the community.' },
        { name: 'intro', type: 'textarea', defaultValue: 'A few moments, talks and builds from previous GDG Nairobi events.' },
        {
          name: 'photos',
          type: 'array',
          dbName: 'highlight_photos',
          maxRows: 9,
          admin: { description: 'Use 4–9 strong images. The first and fourth images receive more space in the grid.' },
          fields: [
            { name: 'image', type: 'upload', relationTo: 'media', required: true },
            { name: 'caption', type: 'text' },
          ],
        },
        {
          name: 'videos',
          type: 'array',
          dbName: 'highlight_videos',
          maxRows: 3,
          admin: { description: 'Displayed in this order and numbered automatically as 01, 02 and 03.' },
          fields: [
            { name: 'title', type: 'text', required: true },
            { name: 'url', type: 'text', required: true, admin: { description: 'YouTube watch, youtu.be, Shorts, or embed URL.' } },
            { name: 'label', type: 'text', defaultValue: 'Watch video' },
          ],
        },
      ],
    },
    {
      name: 'closingSection',
      type: 'group',
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'kicker', type: 'text', defaultValue: 'Nairobi / 2026' },
        { name: 'heading', type: 'text', defaultValue: 'Come curious.' },
        { name: 'accentLine', type: 'text', defaultValue: 'Leave connected.' },
        { name: 'primaryLabel', type: 'text', defaultValue: 'Stay in the loop' },
        { name: 'primaryURL', type: 'text' },
        { name: 'secondaryLabel', type: 'text', defaultValue: 'Partner with DevFest' },
        { name: 'secondaryURL', type: 'text', defaultValue: '/partners' },
      ],
    },
    {
      name: 'statistics',
      type: 'array',
      maxRows: 6,
      fields: [
        { name: 'value', type: 'text', required: true },
        { name: 'label', type: 'text', required: true },
      ],
    },
    {
      name: 'featuredCommunityEvent',
      type: 'relationship',
      relationTo: 'community-events',
      filterOptions: { showOnSite: { equals: true } },
    },
  ],
  versions: {
    drafts: { autosave: true, schedulePublish: true },
    maxPerDoc: 30,
  },
}
