/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'devfest-editions': DevfestEdition;
    speakers: Speaker;
    sessions: Session;
    partners: Partner;
    'team-members': TeamMember;
    announcements: Announcement;
    'community-events': CommunityEvent;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'community-events': {
      sessions: 'sessions';
      eventPage: 'devfest-editions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'devfest-editions': DevfestEditionsSelect<false> | DevfestEditionsSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'community-events': CommunityEventsSelect<false> | CommunityEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Photographer, illustrator, or source credit when required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Optional campaign presentation for a canonical event. Dates, venue, sessions and live operations belong to the linked event.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devfest-editions".
 */
export interface DevfestEdition {
  id: number;
  /**
   * The single canonical DevFest event record used across the website.
   */
  event?: (number | null) | CommunityEvent;
  title: string;
  year: number;
  slug: string;
  status: 'announcement' | 'cfp-open' | 'registration-open' | 'live' | 'ended';
  hero: {
    eyebrow?: string | null;
    headline: string;
    accentLine: string;
    description: string;
    artwork?: (number | null) | Media;
    signals?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    scrollLabel?: string | null;
  };
  eventDetails?: {
    startsAt?: string | null;
    endsAt?: string | null;
    venueName?: string | null;
    address?: string | null;
    mapURL?: string | null;
    locationLabel?: string | null;
  };
  callsToAction?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  ticker?: {
    enabled?: boolean | null;
    items?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  storySection?: {
    enabled?: boolean | null;
    kicker?: string | null;
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
  };
  tracksSection?: {
    enabled?: boolean | null;
    kicker?: string | null;
    heading?: string | null;
    intro?: string | null;
  };
  tracks?:
    | {
        title: string;
        description: string;
        accent: 'blue' | 'red' | 'yellow' | 'green';
        topics?: string[] | null;
        id?: string | null;
      }[]
    | null;
  experienceSection?: {
    enabled?: boolean | null;
    kicker?: string | null;
    heading?: string | null;
    marker?: string | null;
    markerLabel?: string | null;
    items?:
      | {
          eyebrow: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  cfpSection?: {
    enabled?: boolean | null;
    badge?: string | null;
    kicker?: string | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaURL?: string | null;
    artLabelTop?: string | null;
    artLabelBottom?: string | null;
  };
  eventsSection?: {
    enabled?: boolean | null;
    kicker?: string | null;
    heading?: string | null;
    allEventsLabel?: string | null;
    allEventsURL?: string | null;
    syncNote?: string | null;
  };
  /**
   * Curate the homepage photo wall and up to three featured videos.
   */
  highlightsSection?: {
    enabled?: boolean | null;
    kicker?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Use 4–9 strong images. The first and fourth images receive more space in the grid.
     */
    photos?:
      | {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Displayed in this order and numbered automatically as 01, 02 and 03.
     */
    videos?:
      | {
          title: string;
          /**
           * YouTube watch, youtu.be, Shorts, or embed URL.
           */
          url: string;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  closingSection?: {
    enabled?: boolean | null;
    kicker?: string | null;
    heading?: string | null;
    accentLine?: string | null;
    primaryLabel?: string | null;
    primaryURL?: string | null;
    secondaryLabel?: string | null;
    secondaryURL?: string | null;
  };
  statistics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  featuredCommunityEvent?: (number | null) | CommunityEvent;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The canonical home for every GDG Nairobi event, including DevFest. Sync, schedule, venue and live operations all live here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-events".
 */
export interface CommunityEvent {
  id: number;
  source: 'manual' | 'bevy';
  /**
   * Used to match synchronized events. Leave empty for locally managed events.
   */
  upstreamURL?: string | null;
  sourceTitle?: string | null;
  sourceStartDate?: string | null;
  sourceType?: string | null;
  registrationURL?: string | null;
  imageURL?: string | null;
  excerpt?: string | null;
  upstreamStatus?: ('live' | 'completed' | 'stale') | null;
  lastSyncedAt?: string | null;
  showOnSite?: boolean | null;
  featured?: boolean | null;
  eventKind: 'community' | 'workshop' | 'devfest' | 'io-extended' | 'build-with-ai';
  /**
   * Optional short label such as “Workshop” or “Community day”.
   */
  localLabel?: string | null;
  displayOrder?: number | null;
  /**
   * Choose one destination for the event card. The synced Community event remains the canonical record.
   */
  eventDestination: 'community' | 'schedule';
  /**
   * Generated from the title when the internal schedule is enabled.
   */
  slug?: string | null;
  scheduleMode?: ('single' | 'multi') | null;
  /**
   * Optional public title override; the synchronized title is used when empty.
   */
  localTitle?: string | null;
  /**
   * Optional. Useful when the public date changes without changing the upstream record.
   */
  localStartDate?: string | null;
  /**
   * Optional destination when there is no upstream URL or registration moves elsewhere.
   */
  localRegistrationURL?: string | null;
  localDescription?: string | null;
  venueName?: string | null;
  venueAddress?: string | null;
  liveStatus?: ('scheduled' | 'delayed' | 'live' | 'complete') | null;
  /**
   * Live control: set the actual start time and every session moves by the same amount. Clear it to use the planned times.
   */
  scheduleStartOverride?: string | null;
  /**
   * Optional fine adjustment. The actual start control above takes priority when set.
   */
  scheduleOffsetMinutes?: number | null;
  /**
   * Short public message, for example “Running 15 minutes behind”.
   */
  scheduleNotice?: string | null;
  /**
   * Create and update this event’s sessions without leaving the event management screen.
   */
  sessions?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Optional DevFest campaign presentation attached to this event—not a second event record.
   */
  eventPage?: {
    docs?: (number | DevfestEdition)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Sessions belong to an internal event schedule. Times are the planned times; use the event delay control to shift the whole live schedule.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty only for the standalone DevFest programme.
   */
  event?: (number | null) | CommunityEvent;
  speakers?: (number | Speaker)[] | null;
  startsAt: string;
  endsAt: string;
  room: string;
  /**
   * For multi-track events, use any organizer-friendly label such as “Main Stage” or “Workshop Room”.
   */
  scheduleTrack?: string | null;
  track: 'ai' | 'web-mobile' | 'cloud' | 'open';
  format: 'talk' | 'workshop' | 'keynote' | 'panel' | 'break';
  level?: ('all' | 'beginner' | 'intermediate' | 'advanced') | null;
  sessionStatus?: ('scheduled' | 'delayed' | 'live' | 'complete' | 'cancelled') | null;
  /**
   * Short live note such as “Moved to Room B” or “Starting in 10 minutes”.
   */
  publicNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reusable speaker profiles. Updates flow through to every linked event session.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  slug: string;
  portrait?: (number | null) | Media;
  jobTitle?: string | null;
  company?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  topics?: string[] | null;
  featured?: boolean | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Logo URL from the official GDG Nairobi chapter page when no local media asset has been uploaded.
   */
  sourceLogoURL?: string | null;
  url?: string | null;
  scope: 'chapter' | 'devfest';
  tier: 'host' | 'platinum' | 'gold' | 'silver' | 'community';
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  order: number;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  message: string;
  kind?: ('info' | 'cfp' | 'tickets' | 'urgent') | null;
  startsAt?: string | null;
  endsAt?: string | null;
  linkLabel?: string | null;
  linkURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'devfest-editions';
        value: number | DevfestEdition;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'community-events';
        value: number | CommunityEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devfest-editions_select".
 */
export interface DevfestEditionsSelect<T extends boolean = true> {
  event?: T;
  title?: T;
  year?: T;
  slug?: T;
  status?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        accentLine?: T;
        description?: T;
        artwork?: T;
        signals?:
          | T
          | {
              label?: T;
              id?: T;
            };
        scrollLabel?: T;
      };
  eventDetails?:
    | T
    | {
        startsAt?: T;
        endsAt?: T;
        venueName?: T;
        address?: T;
        mapURL?: T;
        locationLabel?: T;
      };
  callsToAction?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  ticker?:
    | T
    | {
        enabled?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  storySection?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        quote?: T;
      };
  tracksSection?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
      };
  tracks?:
    | T
    | {
        title?: T;
        description?: T;
        accent?: T;
        topics?: T;
        id?: T;
      };
  experienceSection?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        marker?: T;
        markerLabel?: T;
        items?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  cfpSection?:
    | T
    | {
        enabled?: T;
        badge?: T;
        kicker?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaURL?: T;
        artLabelTop?: T;
        artLabelBottom?: T;
      };
  eventsSection?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        allEventsLabel?: T;
        allEventsURL?: T;
        syncNote?: T;
      };
  highlightsSection?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        intro?: T;
        photos?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        videos?:
          | T
          | {
              title?: T;
              url?: T;
              label?: T;
              id?: T;
            };
      };
  closingSection?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        heading?: T;
        accentLine?: T;
        primaryLabel?: T;
        primaryURL?: T;
        secondaryLabel?: T;
        secondaryURL?: T;
      };
  statistics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  featuredCommunityEvent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  portrait?: T;
  jobTitle?: T;
  company?: T;
  bio?: T;
  topics?: T;
  featured?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  event?: T;
  speakers?: T;
  startsAt?: T;
  endsAt?: T;
  room?: T;
  scheduleTrack?: T;
  track?: T;
  format?: T;
  level?: T;
  sessionStatus?: T;
  publicNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  sourceLogoURL?: T;
  url?: T;
  scope?: T;
  tier?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  order?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  kind?: T;
  startsAt?: T;
  endsAt?: T;
  linkLabel?: T;
  linkURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-events_select".
 */
export interface CommunityEventsSelect<T extends boolean = true> {
  source?: T;
  upstreamURL?: T;
  sourceTitle?: T;
  sourceStartDate?: T;
  sourceType?: T;
  registrationURL?: T;
  imageURL?: T;
  excerpt?: T;
  upstreamStatus?: T;
  lastSyncedAt?: T;
  showOnSite?: T;
  featured?: T;
  eventKind?: T;
  localLabel?: T;
  displayOrder?: T;
  eventDestination?: T;
  slug?: T;
  scheduleMode?: T;
  localTitle?: T;
  localStartDate?: T;
  localRegistrationURL?: T;
  localDescription?: T;
  venueName?: T;
  venueAddress?: T;
  liveStatus?: T;
  scheduleStartOverride?: T;
  scheduleOffsetMinutes?: T;
  scheduleNotice?: T;
  sessions?: T;
  eventPage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  brandLabel: string;
  editionLabel: string;
  currentEdition?: (number | null) | DevfestEdition;
  navigation?:
    | {
        label: string;
        url: string;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerCTA: {
    label: string;
    url: string;
  };
  communityHomepage?: {
    hero?: {
      eyebrow?: string | null;
      headline?: string | null;
      accentLine?: string | null;
      description?: string | null;
      primaryLabel?: string | null;
      primaryURL?: string | null;
      secondaryLabel?: string | null;
      secondaryURL?: string | null;
    };
    statistics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    about?: {
      kicker?: string | null;
      heading?: string | null;
      description?: string | null;
    };
    pillars?:
      | {
          title: string;
          description: string;
          accent: 'blue' | 'red' | 'yellow' | 'green';
          id?: string | null;
        }[]
      | null;
    ecosystem?: {
      kicker?: string | null;
      heading?: string | null;
      description?: string | null;
      items?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    closing?: {
      kicker?: string | null;
      heading?: string | null;
      accentLine?: string | null;
      primaryLabel?: string | null;
      primaryURL?: string | null;
      secondaryLabel?: string | null;
      secondaryURL?: string | null;
    };
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    groups?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                url: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  brandLabel?: T;
  editionLabel?: T;
  currentEdition?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        enabled?: T;
        id?: T;
      };
  headerCTA?:
    | T
    | {
        label?: T;
        url?: T;
      };
  communityHomepage?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              accentLine?: T;
              description?: T;
              primaryLabel?: T;
              primaryURL?: T;
              secondaryLabel?: T;
              secondaryURL?: T;
            };
        statistics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        about?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
            };
        pillars?:
          | T
          | {
              title?: T;
              description?: T;
              accent?: T;
              id?: T;
            };
        ecosystem?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        closing?:
          | T
          | {
              kicker?: T;
              heading?: T;
              accentLine?: T;
              primaryLabel?: T;
              primaryURL?: T;
              secondaryLabel?: T;
              secondaryURL?: T;
            };
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        groups?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        note?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'devfest-editions';
          value: number | DevfestEdition;
        } | null)
      | ({
          relationTo: 'speakers';
          value: number | Speaker;
        } | null)
      | ({
          relationTo: 'sessions';
          value: number | Session;
        } | null)
      | ({
          relationTo: 'partners';
          value: number | Partner;
        } | null)
      | ({
          relationTo: 'team-members';
          value: number | TeamMember;
        } | null)
      | ({
          relationTo: 'announcements';
          value: number | Announcement;
        } | null);
    global?: 'site-settings' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}